version: "3"
services:

  pug:
    build:
      context: .
      dockerfile: 'pug.dockerfile'
    volumes:
      - ./:/site
    command: ["pug", "--watch", "--pretty", "--basedir", "./src/includes", "--out", "./dist", "./src"]

  sass:
    build:
      context: .
      dockerfile: 'sass.dockerfile'
    volumes:
      - ./:/site
    command: ["sass", "--watch", "src/scss:dist/css"]
